# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21


      - name: Install dependencies
        run: |
          go mod download

      - name: Run Go Vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

  publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Username }}
          password: ${{ secrets.Ralphiko }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: C:\Users\iburb\Final-main1  

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: C:\Users\iburb\Final-main1  
          push: true
          tags: ralphiko/final-main1:${{ github.sha }}
          labels: org.opencontainers.image.created=${{ github.run_at }}
    

          
